# python train_net.py --config-file configs/semantic/train_semantic_base.yaml  --num-gpus 8 

_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  META_ARCHITECTURE: "MAFT_Plus"  # FCCLIP MAFT_Plus
  SEM_SEG_HEAD:
    NAME: "FCCLIPHead"
    NUM_CLASSES: 171
  OPEN_MAMBA:
    NAME: "OpenMambaHead"
    MASK_IN_CHANNELS: 16
    NUM_CHANNELS: 768
    USE_CHECKPOINT: False
    NUM_OUTPUT_MAPS: 16
    MASK_THRESHOLD: 0.45
    VSSD:
      IMAGE_SIZE: 32
      PATCH_SIZE: 2
      IN_CHANS: 768
      EMBED_DIM: 48
      DEPTHS: [2, 2, 8, 4]
      NUM_HEADS: [2, 4, 8, 16]
      MLP_RATIO: 4.0
      DROP_RATE: 0.0
      DROP_PATH_RATE: 0.2
      SIMPLE_DOWNSAMPLE: False
      SIMPLE_PATCH_EMBED: False
      SSD_EXPANSION: 2
      SSD_NGROUPS: 1
      SSD_CHUNK_SIZE: 256
      LINEAR_ATTN_DUALITY: True
      LEPE: False
      ATTN_TYPES: ['mamba2', 'mamba2', 'mamba2', 'standard']
      BIDIRECTION: False
      D_STATE: 48
      SSD_POSITIVE_DA: True
    MCA:
      DIMS: [48,96,192,384]
      TEXTUAL_DIM: 640
      INPUT_RESOLUTIONS: [[8,8], [4,4], [2,2], [1,1]]
      ATTN_TYPES: ['mamba2', 'mamba2', 'mamba2', 'standard']
      NUM_HEADS: 4
      MLP_RATIO: 4.
      QKV_BIAS: True
      DROP: 0.
      DROP_PATH: 0.2 
      SSD_EXPANSION: 2 
      SSD_NGROUPS: 1
      SSD_CHUNK_SIZE: 256
      LINEAR_ATTN_DUALITY: True
      D_STATES: [24,48,96,192]
      USE_CHECKPOINT: False
  FC_CLIP:
    CLIP_MODEL_NAME: "convnext_base_w_320"  
    CLIP_PRETRAINED_WEIGHTS: "laion_aesthetic_s13b_b82k_augreg"   
    EMBED_DIM: 640
    GEOMETRIC_ENSEMBLE_ALPHA: 0.7
    GEOMETRIC_ENSEMBLE_BETA: 1.0
  rc_weights: 0.1
  MASK_FORMER:
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OBJECT_MASK_THRESHOLD: 0.0
  cdt_params:
  - 640
  - 8

INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic" # mask_former_semantic coco_panoptic_lsj
DATASETS:
  TRAIN: ("openvocab_coco_2017_train_stuff_sem_seg",)  
  TEST: ('openvocab_ade20k_panoptic_val',)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00005
  STEPS: (43371, 47314)
  MAX_ITER: 49286
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic"  #
OUTPUT_DIR: ./training/maftp-base/ade20k